# Generated by Django 5.1.4 on 2025-02-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('Complete', models.BooleanField(default=False)),
            ],
        ),
    ]
